name: Deploy MVP EventBridge Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Trigger Test Event
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloud-formation/mvp-eventbridge.yaml \
            --stack-name eventbridge-mvp-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Send Test Event to EventBridge
        if: success()
        run: |
          echo '[
            {
              "Source": "manual.test",
              "DetailType": "initiate",
              "Detail": "{\"message\":\"hello from github actions\"}",
              "EventBusName": "event-bus"
            }
          ]' > test-event.json
          aws events put-events --entries file://test-event.json

      - name: Debug Stack Events on Failure
        if: failure()
        run: |
          echo "CloudFormation stack creation failed. Fetching error events..."
          aws cloudformation describe-stack-events \
            --stack-name eventbridge-mvp-stack \
            --region us-east-1
